let tagDisplayName = {
	"ac": "AC",
	"airconditioning": "Air conditioning",
	"amusementpark": "Amusement park",
	"ancient": "Ancient",
	"animal": "Animal",
	"animalfloor": "Animal floor",
	"antique": "Antique",
	"apparelshop": "Apparel shop",
	"apple": "Apple",
	"appliance": "Appliance",
	"arcade": "Arcade",
	"arch": "Arch",
	"archedbrick": "Arched brick",
	"argyle": "Argyle",
	"artdecowalls": "Art deco walls",
	"artsy": "Artsy",
	"asia": "Asia",
	"audio": "Audio",
	"bamboo": "Bamboo",
	"bathroom": "Bathroom",
	"bathroomthings": "Bathroom things",
	"bathtub": "Bathtub",
	"bear": "Bear",
	"bed": "Bed",
	"birthday": "Birthday",
	"brick": "Brick",
	"bromide": "Bromide",
	"bughead": "Bughead",
	"bunnyday": "Bunny day",
	"café": "Café",
	"camouflage": "Camouflage",
	"cardboard": "Cardboard",
	"castle": "Castle",
	"ceilingetc": "Ceiling etc.",
	"ceilinglamp": "Ceiling lamp",
	"chair": "Chair",
	"chalkboard": "Chalkboard",
	"cherry": "Cherry",
	"cherryblossoms": "Cherry blossoms",
	"chest": "Chest",
	"childsroom": "Child's room",
	"chocolate": "Chocolate",
	"cinnamoroll": "Cinnamoroll",
	"citylife": "City life",
	"clock": "Clock",
	"clothfloors": "Cloth floors",
	"clothwalls": "Cloth walls",
	"colorfulwood": "Colorful wood",
	"comfy": "Comfy",
	"compass": "Compass",
	"concert": "Concert",
	"constructionsite": "Construction site",
	"cool": "Cool",
	"counter": "Counter",
	"country": "Country",
	"crownwalls": "Crown walls",
	"cute": "Cute",
	"cutewalls": "Cute walls",
	"decadence": "Decadence",
	"decowood": "Deco wood",
	"den": "Den",
	"desk": "Desk",
	"diner": "Diner",
	"dinerwalls": "Diner walls",
	"dining": "Dining",
	"dishdrink": "Dish drink",
	"dishfood": "Dish food",
	"doll": "Doll",
	"dollhousewalls": "Dollhouse walls",
	"dot": "Dot",
	"dreamy": "Dreamy",
	"dresser": "Dresser",
	"easter": "Easter",
	"elegant": "Elegant",
	"etc": "Etc.",
	"european": "European",
	"everyday": "Everyday",
	"expensive": "Expensive",
	"facility": "Facility",
	"facilitydecor": "Facility decor",
	"fairytale": "Fairy tale",
	"fan": "Fan",
	"fancy": "Fancy",
	"fantasy": "Fantasy",
	"festivale": "Festivale",
	"festive": "Festive",
	"fieldvine": "Vine",
	"fieldweedlight": "Weed light",
	"fireplace": "Fireplace",
	"fish": "Fish",
	"fitness": "Fitness",
	"floorsimpleglodsilverbronze": "Floor simple gold silver bronze", //typo in key?
	"flowerpopwalls": "Flower-pop walls",
	"flowers": "Flowers",
	"flowerwalls": "Flower walls",
	"folkcraftdecor": "Folk craft decor",
	"food": "Food",
	"formal": "Formal",
	"fossilunknown": "Fossil unknown",
	"freezingcold": "Freezing cold",
	"frozen": "Frozen",
	"fruitrugs": "Fruit rugs",
	"fruits": "Fruits",
	"fruitwalls": "Fruit walls",
	"ftrwall": "Ftrwall",
	"gameconsole": "Game console",
	"gaming": "Gaming",
	"garden": "Garden",
	"golden": "Golden",
	"goth": "Goth",
	"grassland": "Grassland",
	"hallwalls": "Hall walls",
	"haniwa": "Gyroid",
	"haniwapiece": "Gyroid fragment",
	"harmonious": "Harmonious",
	"heartrugs": "Heart rugs",
	"heartwalls": "Heart walls",
	"heating": "Heating",
	"hellokitty": "Hello Kitty",
	"heritage": "Heritage",
	"herringbone": "Herringbone",
	"homeappliances": "Home appliances",
	"honeycomb": "Honeycomb",
	"horror": "Horror",
	"hospital": "Hospital",
	"housedoordecor": "House door decor",
	"iconrugs": "Icon rugs",
	"imperial": "Imperial",
	"imperialdining": "Imperial dining",
	"insect": "Insect",
	"iron": "Iron",
	"irongarden": "Iron garden",
	"ironparquet": "Iron-parquet",
	"ironwalls": "Iron walls",
	"ironwood": "Ironwood",
	"japanese": "Japanese",
	"japanesestyle": "Japanese-style",
	"kerokerokeroppi": "Kerokerokeroppi",
	"kiki&lala": "Kiki and Lala",
	"kitchen": "Kitchen",
	"kitchenfloors": "Kitchen floors",
	"kitchenrugs": "Kitchen rugs",
	"kitchenthings": "Kitchen things",
	"lab": "Lab",
	"lamp": "Lamp",
	"lecturehall": "Lecture hall",
	"librarywalls": "Library walls",
	"lighting": "Lighting",
	"livingroom": "Living room",
	"local": "Local",
	"log": "Log",
	"luxury": "Luxury",
	"machinefloor": "Machine floor",
	"manorwalls": "Manor walls",
	"mario": "Mario",
	"mermaid": "Mermaid",
	"messagemats": "Message mats",
	"metalandwood": "Metal-and-wood",
	"metrowalls": "Metro walls",
	"moroccan": "Moroccan",
	"morocco": "Morocco",
	"motherly": "Motherly",
	"museum": "Museum",
	"mush": "Mush",
	"music": "Music",
	"musicalinstrument": "Musical instrument",
	"mymelody": "My Melody",
	"natural": "Natural",
	"nature": "Nature",
	"naturebrown": "Nature brown",
	"naturefallenleaves": "Nature fallen leaves",
	"naturegreen": "Nature green",
	"naturewalls": "Nature walls",
	"naturewhite": "Nature white",
	"neta": "Neta",
	"netawalls": "Neta walls",
	"nordic": "Nordic",
	"ocean": "Ocean",
	"office": "Office",
	"orange": "Orange",
	"outdoors": "Outdoors",
	"outdoorsy": "Outdoorsy",
	"paintedwood": "Painted wood",
	"panda": "Panda",
	"panel": "Panel",
	"panelmoldwalls": "Molded-panel",
	"park": "Park",
	"parkrugs": "Park rugs",
	"parquet": "Parquet",
	"party": "Party",
	"patchwork": "Patchwork",
	"patternrugs": "Pattern rugs",
	"peach": "Peach",
	"pear": "Pear",
	"pegboardwalls": "Pegboard walls",
	"pet": "Pet",
	"picture": "Picture",
	"pillar": "Pillar",
	"pirate": "Pirate",
	"plant": "Plant",
	"plants": "Plants",
	"playground": "Playground",
	"plaza": "Plaza",
	"pompompurin": "Pompompurin",
	"posters": "Posters",
	"publicbath": "Public bath",
	"puzzlemat": "Puzzle mat",
	"puzzlewalls": "Puzzle walls",
	"ranch": "Ranch",
	"rattan": "Rattan",
	"resort": "Resort",
	"restaurant": "Restaurant",
	"retro": "Retro",
	"roserug": "Rose rug",
	"rosewalls": "Rose walls",
	"rubber": "Rubber",
	"ruined": "Ruined",
	"sanriofloor": "Sanrio floor",
	"sanriorugs": "Sanrio rugs",
	"sanriowalls": "Sanrio walls",
	"school": "School",
	"scifi": "Sci-fi",
	"screen": "Screen",
	"sculpture": "Sculpture",
	"seaside": "Seaside",
	"seasonaldecor": "Seasonal decor",
	"shaggyroundrugs": "Shaggy round rugs",
	"shelf": "Shelf",
	"shell": "Shell",
	"shop": "Shop",
	"sidewalk": "Sidewalk",
	"simple": "Simple",
	"simplecarpet": "Simple carpet",
	"simpleparquet": "Simple parquet",
	"simplerugs": "Simple rugs",
	"simplewalls": "Simple walls",
	"slenderpatternrugs": "Slender pattern rugs",
	"slenderrugs": "Slender rugs",
	"sloppy": "Sloppy",
	"smallgoods": "Small goods",
	"sofa": "Sofa",
	"space": "Space",
	"specialcoolnaturewalls": "Special cool nature walls",
	"specialfish": "Special fish",
	"specialinorganicfloors": "Special inorganic floors",
	"specialinorganicwalls": "Special inorganic walls",
	"specialinsect": "Special insect",
	"specialnaturefloors": "Special nature floors",
	"specialwalls": "Special walls",
	"specialwarmnaturewalls": "Special warm nature walls",
	"spooky": "Spooky",
	"sports": "Sports",
	"sportsfloor": "Sports floor",
	"sportsring": "Sports ring",
	"sporty": "Sporty",
	"standee": "Standee",
	"stars": "Stars",
	"stone": "Stone",
	"stonefloors": "Stone floors",
	"stonewalls": "Stone walls",
	"stripewalls": "Stripe walls",
	"stuccowalls": "Stucco walls",
	"study": "Study",
	"stylish": "Stylish",
	"supermarket": "Supermarket",
	"supplies": "Supplies",
	"table": "Table",
	"tableclock": "Table clock",
	"tatami": "Tatami",
	"tatamipanel": "Tatami panel",
	"tearoomwalls": "Tearoom walls",
	"theatrical": "Theatrical",
	"throwback": "Throwback",
	"tilechecker": "Checker tile",
	"tilefloors": "Tile floors",
	"tilewalls": "Tile walls",
	"tinwalls": "Tin walls",
	"toilet": "Toilet",
	"toy": "Toy",
	"toywalls": "Toy walls",
	"trash": "Trash",
	"treesbountyorleaves": "Tree's bounty or leaves",
	"turkeyday": "Turkey day",
	"tv": "TV",
	"twotonetilewalls": "Two-tone tile walls",
	"vacation": "Vacation",
	"vehicle": "Vehicle",
	"vintage": "Vintage",
	"wallfacility": "Wall facility",
	"wallgoldsilverbronze": "Wall gold silver bronze",
	"wedding": "Wedding",
	"wooden": "Wooden",
	"woodenblock": "Wooden block",
	"woodfloors": "Wood floors",
	"woodplankwalls": "Wood plank walls",
	"woodrugs": "Wood rugs",
	"woodtilewalls": "Wood tile walls",
	"woodwalls": "Wood walls",
	"work": "Work",
	"workbench": "Workbench",
	"workshop": "Workshop",
	
	"fruit": "Fruit",
	"tree": "Tree",
	"flower": "Flower",
	"cosmos": "Cosmos",
	"lily": "Lily",
	"rose": "Rose",
	"tulip": "Tulip",
	"hyacinth": "Hyacinth",
	"bush": "Bush",
	"hydrangea": "Hydrangea",
	"pansy": "Pansy",
	"windflower": "Windflower",
	"vegetable": "Vegetable",
	"carrot": "Carrot",
	"mum": "Mum",
	"holly": "Holly",
	"potato": "Potato",
	"pumpkin": "Pumpkin",
	"sugarcane": "Sugarcane",
	"tomato": "Tomato",
	"wheat": "Wheat",
	"teaolive": "Tea olive",
	"azalea": "Azalea",
	"camellia": "Camellia",
	"plumeria": "Plumeria",
	"hibiscus": "Hibiscus",
	
	"ぞうきんがけ": "ぞうきんがけ"
};